import Navigation from "../components/navigation"
import '../style/global.css'

export const metadata = {
  title: {
    template: '%s | Next Example',
    default: 'Next Example'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
